version: '3'
services:
  locust-master:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - locust
      - --host=https://dev-dunder-mifflin-drupal.pantheonsite.io
      - -f
      - locustfile.py
      - --master
    ports:
      - "8089:8089"
  locust-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - locust
      - --worker
      - --master-host=locust-master
    depends_on:
      - locust-master
  locust-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - locust
      - --worker
      - --master-host=locust-master
    depends_on:
      - locust-master
  locust-worker-3:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - locust
      - --worker
      - --master-host=locust-master
    depends_on:
      - locust-master
  locust-worker-4:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - locust
      - --worker
      - --master-host=locust-master
    depends_on:
      - locust-master
  locust-worker-5:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - locust
      - --worker
      - --master-host=locust-master
    depends_on:
      - locust-master
